import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import { findStudentUploadForReport, getReport } from './history.service.js'
import { ApiError } from '../utils/api-error.js'

const orange = rgb(0.85, 0.47, 0.34); const red = rgb(0.86, 0.15, 0.15); const blue = rgb(0.16, 0.42, 0.75); const green = rgb(0.09, 0.64, 0.29); const ink = rgb(0.16, 0.14, 0.13)
function wrap(text: string, width: number, font: { widthOfTextAtSize(value: string, size: number): number }, size: number) { const words = text.split(/\s+/); const lines: string[] = []; let current = ''; for (const word of words) { const candidate = current ? `${current} ${word}` : word; if (font.widthOfTextAtSize(candidate, size) > width && current) { lines.push(current); current = word } else current = candidate } if (current) lines.push(current); return lines }
function drawTextLines(page: import('pdf-lib').PDFPage, text: string, x: number, y: number, width: number, font: import('pdf-lib').PDFFont, size = 10, color = ink) { let cursor = y; for (const line of wrap(text, width, font, size)) { page.drawText(line, { x, y: cursor, size, font, color }); cursor -= size + 4 } return cursor }

export async function createAnnotatedReport(reportId: string): Promise<{ bytes: Uint8Array; filename: string }> {
  const report = getReport(reportId); if (!report) throw new ApiError(404, 'Grading report was not found.')
  const upload = findStudentUploadForReport(report.createdAt); if (!upload) throw new ApiError(404, 'The original student answer file was not found.')
  const source = await readFile(resolve(process.cwd(), upload.path))
  const document = await PDFDocument.create()
  if (upload.mimeType === 'application/pdf') { const sourceDocument = await PDFDocument.load(source); const pages = await document.copyPages(sourceDocument, sourceDocument.getPageIndices()); pages.forEach(page => document.addPage(page)) } else if (upload.mimeType === 'image/png' || upload.mimeType === 'image/jpeg') { const image = upload.mimeType === 'image/png' ? await document.embedPng(source) : await document.embedJpg(source); const page = document.addPage([595, 842]); const scale = Math.min((page.getWidth() - 56) / image.width, (page.getHeight() - 56) / image.height); page.drawImage(image, { x: 28, y: (page.getHeight() - image.height * scale) / 2, width: image.width * scale, height: image.height * scale }) } else throw new ApiError(400, 'The student answer file cannot be exported.')
  const font = await document.embedFont(StandardFonts.Helvetica); const bold = await document.embedFont(StandardFonts.HelveticaBold)
  const firstPage = document.getPage(0); const { width, height } = firstPage.getSize(); const evidence = report.grading.evidence.slice(0, 4)
  evidence.forEach((item, index) => { const color = index === 0 ? orange : index === 1 ? red : index === 2 ? blue : green; const y = height - 100 - index * 82; firstPage.drawLine({ start: { x: 64, y }, end: { x: Math.min(width - 170, 64 + width * 0.46), y }, thickness: 2.5, color }); firstPage.drawCircle({ x: 48, y, size: 10, color }); firstPage.drawText(String(index + 1), { x: 45, y: y - 3.5, size: 8, font: bold, color: rgb(1, 1, 1) }); firstPage.drawRectangle({ x: width - 158, y: y - 22, width: 136, height: 44, color: rgb(1, 0.99, 0.98), borderColor: color, borderWidth: 0.7 }); drawTextLines(firstPage, item.reason, width - 151, y + 11, 122, font, 7, ink) })
  const summary = document.addPage([595, 842]); summary.drawText('GradeSense Report', { x: 48, y: 790, size: 24, font: bold, color: ink }); summary.drawText(`${report.studentName} - ${report.assignment}`, { x: 48, y: 765, size: 11, font, color: rgb(0.4, 0.37, 0.34) }); summary.drawText(`${report.score}/20`, { x: 48, y: 704, size: 34, font: bold, color: orange }); summary.drawText(`${report.percentage}% overall | ${report.confidence}% OCR confidence`, { x: 48, y: 680, size: 11, font, color: ink }); let y = 635; summary.drawText('AI Summary', { x: 48, y, size: 14, font: bold, color: ink }); y = drawTextLines(summary, report.grading.summary, 48, y - 20, 500, font, 10); y -= 18; summary.drawText('Strengths', { x: 48, y, size: 14, font: bold, color: ink }); y = drawTextLines(summary, report.grading.strengths.join(' • '), 48, y - 20, 500, font, 10); y -= 18; summary.drawText('Improvements', { x: 48, y, size: 14, font: bold, color: ink }); y = drawTextLines(summary, report.grading.improvements.join(' • '), 48, y - 20, 500, font, 10); y -= 18; summary.drawText('Rubric Breakdown', { x: 48, y, size: 14, font: bold, color: ink }); y -= 22; report.grading.rubricBreakdown.forEach(item => { summary.drawText(item.criterion, { x: 48, y, size: 10, font: bold, color: ink }); summary.drawText(String(item.score), { x: 500, y, size: 10, font: bold, color: orange }); y = drawTextLines(summary, item.feedback, 48, y - 14, 440, font, 8, rgb(0.4, 0.37, 0.34)); y -= 10 })
  return { bytes: await document.save(), filename: `GradeSense_Report_${report.studentName.replace(/[^a-z0-9]+/gi, '_')}.pdf` }
}
