import { History, LayoutDashboard, Menu, Sparkles } from 'lucide-react'
import { useState, type ReactNode } from 'react'
import { NavLink, useLocation } from 'react-router-dom'
import { Button } from '../ui/Button'

const navigation = [{ label: 'Grade Answer', to: '/', icon: LayoutDashboard }, { label: 'History', to: '/history', icon: History }]
export function AppLayout({ children }: { children: ReactNode }) {
  const [open, setOpen] = useState(false); const location = useLocation()
  return <div className="min-h-screen bg-[#FCFBFA] lg:flex"><aside className={`fixed inset-y-0 left-0 z-40 flex w-72 flex-col border-r bg-white p-5 transition-transform lg:static lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}><div className="flex items-center gap-2.5 px-2"><span className="grid size-9 place-items-center rounded-xl bg-[#D97757] text-white"><Sparkles className="size-4" /></span><span className="font-semibold tracking-tight">GradeSense <span className="text-[#D97757]">AI</span></span></div><nav className="mt-10 space-y-1" aria-label="Main navigation">{navigation.map(({ label, to, icon: Icon }) => <NavLink key={to} to={to} onClick={() => setOpen(false)} className={({ isActive }) => `flex h-11 items-center gap-3 rounded-xl px-3 text-sm font-medium transition ${isActive ? 'bg-[#fdf0eb] text-[#bd6247]' : 'text-stone-500 hover:bg-stone-50 hover:text-stone-900'}`}><Icon className="size-4" />{label}</NavLink>)}</nav><div className="mt-auto rounded-2xl bg-stone-50 p-4"><p className="text-xs font-medium">Need a hand?</p><p className="mt-1 text-xs leading-5 text-stone-500">Explore the educator guide for quick tips.</p><a href="#guide" className="mt-3 inline-block text-xs font-medium text-[#bd6247]">Open guide →</a></div></aside>{open && <button aria-label="Close navigation" onClick={() => setOpen(false)} className="fixed inset-0 z-30 bg-stone-950/20 lg:hidden" />}<div className="min-w-0 flex-1"><header className="flex h-20 items-center justify-between border-b bg-[#FCFBFA] px-5 sm:px-8"><div className="flex items-center gap-3"><Button variant="ghost" size="sm" className="lg:hidden !px-2" aria-label="Open navigation" onClick={() => setOpen(true)}><Menu className="size-5" /></Button><p className="text-sm text-stone-500">{location.pathname === '/history' ? 'Grading history' : location.pathname === '/processing' ? 'Preparing your review' : location.pathname === '/results' ? 'Review results' : 'New grading review'}</p></div><button aria-label="Open profile menu" className="grid size-9 place-items-center rounded-full bg-stone-900 text-xs font-semibold text-white">AP</button></header><main className="mx-auto w-full max-w-[1600px] p-5 sm:p-8">{children}</main></div></div>
}
