import { CheckCircle2, FileText, LoaderCircle, Upload } from 'lucide-react'
import { AnimatePresence, motion } from 'framer-motion'
import type { UploadFile } from '../../types/grading'
import { Button } from '../ui/Button'
import { Card } from '../ui/Card'

interface UploadCardProps { label: string; hint: string; file?: UploadFile; pages: string; isUploading?: boolean; onUpload: () => void }

export function UploadCard({ label, hint, file, pages, isUploading = false, onUpload }: UploadCardProps) {
  return <Card className="overflow-hidden p-3 sm:p-4"><AnimatePresence mode="wait">{file ? <motion.div key="success" initial={{ opacity: 0, scale: 0.98 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: 0.98 }} transition={{ duration: 0.25 }} className="flex items-center gap-4 rounded-2xl bg-green-50 p-5"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-white text-[#16A34A] shadow-sm"><CheckCircle2 className="size-5" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-stone-800">{file.name}</p><p className="mt-1 text-xs text-stone-500">{pages} · {file.size} · Uploaded successfully</p></div><Button variant="secondary" size="sm" onClick={onUpload}>Replace</Button></motion.div> : <motion.div key="dropzone" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: 0.25 }}><button type="button" onClick={onUpload} disabled={isUploading} className="flex min-h-[330px] w-full flex-col items-center justify-center rounded-2xl border border-dashed border-[#D8D3CF] bg-[#FCFBFA] p-8 text-center transition hover:border-[#D97757] hover:bg-[#fdf8f5] disabled:cursor-wait"><span className="grid size-14 place-items-center rounded-2xl bg-white text-[#D97757] shadow-sm"><FileText className="size-6" /></span><p className="mt-5 text-base font-semibold text-stone-900">{label}</p><p className="mt-2 max-w-xs text-sm leading-6 text-stone-500">{hint}</p><span className="mt-6"><Button type="button" disabled={isUploading} onClick={event => { event.stopPropagation(); onUpload() }}>{isUploading ? <><LoaderCircle className="size-4 animate-spin" />Uploading…</> : <><Upload className="size-4" />Upload file</>}</Button></span><p className="mt-4 text-xs text-stone-400">PDF, PNG, or JPG · Maximum 20 MB</p></button></motion.div>}</AnimatePresence></Card>
}
