import { Check, Circle, LoaderCircle, Sparkles } from 'lucide-react'
import { motion } from 'framer-motion'
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { ProgressBar } from '../components/ui/ProgressBar'
import type { ProcessingStatus } from '../types/grading'

const stages = ['Reading source documents', 'Extracting handwritten response', 'Matching answer to rubric', 'Preparing feedback and annotations']
export function ProcessingPage() { const [progress, setProgress] = useState(24); const navigate = useNavigate(); useEffect(() => { const timer = window.setInterval(() => setProgress(value => Math.min(value + 7, 92)), 800); return () => window.clearInterval(timer) }, []); const active = Math.min(Math.floor(progress / 25), 3); const status = (index: number): ProcessingStatus => index < active ? 'complete' : index === active ? 'active' : 'pending'; return <div className="mx-auto max-w-3xl pt-4"><div className="text-center"><span className="inline-flex items-center gap-2 text-xs font-medium text-[#bd6247]"><Sparkles className="size-3.5" />GradeSense is working</span><h1 className="mt-3 text-3xl font-semibold tracking-tight">Preparing a careful review</h1><p className="mt-3 text-sm text-stone-500">We’re organising the documents and gathering evidence for your review.</p></div><Card className="mt-10 overflow-hidden p-6 sm:p-8"><div className="flex items-end justify-between"><div><p className="text-sm font-semibold">Processing answer</p><p className="mt-1 text-sm text-stone-500">This usually takes less than a minute.</p></div><span className="text-3xl font-semibold tracking-tight text-[#bd6247]">{progress}%</span></div><ProgressBar value={progress} className="mt-6" /><div className="mt-8 divide-y">{stages.map((stage, index) => { const current = status(index); return <div key={stage} className="flex items-center gap-3 py-4"><span className={`grid size-6 place-items-center rounded-full ${current === 'complete' ? 'bg-green-100 text-green-700' : current === 'active' ? 'bg-[#fdf0eb] text-[#bd6247]' : 'bg-stone-100 text-stone-300'}`}>{current === 'complete' ? <Check className="size-3.5" /> : current === 'active' ? <LoaderCircle className="size-3.5 animate-spin" /> : <Circle className="size-3.5" />}</span><span className={`text-sm ${current === 'pending' ? 'text-stone-400' : 'font-medium'}`}>{stage}</span>{current === 'active' && <span className="ml-auto text-xs text-[#bd6247]">In progress</span>}</div> })}</div></Card><Card className="mt-5 overflow-hidden p-5"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-[#fdf0eb]"><Sparkles className="size-4 text-[#bd6247]" /></div><div><p className="text-sm font-semibold">AI activity</p><p className="text-xs text-stone-500">Checking response against the model answer</p></div></div><motion.div className="mt-5 h-10 rounded-xl bg-gradient-to-r from-stone-100 via-stone-50 to-stone-100" animate={{ backgroundPosition: ['0% 0%', '100% 0%'] }} transition={{ repeat: Infinity, duration: 1.6, ease: 'linear' }} style={{ backgroundSize: '200% 100%' }} /></Card><div className="mt-7 text-center"><Button onClick={() => navigate('/results')}>Finish Processing</Button><p className="mt-3 text-xs text-stone-400">Demo control — results are mock data only.</p></div></div> }
