import { ArrowRight, FileCheck2, Sparkles } from 'lucide-react'
import { motion, AnimatePresence } from 'framer-motion'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { UploadCard } from '../components/upload/UploadCard'
import { Button } from '../components/ui/Button'
import { Stepper } from '../components/ui/Stepper'
import type { UploadFile } from '../types/grading'

const steps = [{ label: 'Question Paper', hint: 'Upload the assignment question paper or prompt.', file: { name: 'industrial-revolution-question.pdf', size: '248 KB' } }, { label: 'Model Answer', hint: 'Upload the exemplar or mark scheme for this question.', file: { name: 'industrial-revolution-model-answer.pdf', size: '184 KB' } }, { label: 'Student Answer', hint: 'Upload the student’s handwritten or typed response.', file: { name: 'amara-patel-response.pdf', size: '1.2 MB' } }]
export function UploadWizardPage() { const [active, setActive] = useState(1); const [uploads, setUploads] = useState<Record<number, UploadFile>>({}); const navigate = useNavigate(); const current = steps[active - 1]; const uploaded = uploads[active]; const allComplete = Object.keys(uploads).length === 3; const upload = () => setUploads(state => ({ ...state, [active]: current.file })); return <div className="mx-auto max-w-2xl"><div className="mb-10"><span className="inline-flex items-center gap-2 text-xs font-medium text-[#bd6247]"><Sparkles className="size-3.5" />AI-assisted grading</span><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Set up a new review</h1><p className="mt-3 text-sm leading-6 text-stone-500">Add the three documents that give GradeSense the context for a fair, evidence-based review.</p></div><Stepper steps={steps.map(s => s.label)} activeStep={active} /><AnimatePresence mode="wait"><motion.div key={active} initial={{ opacity: 0, x: 12 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -12 }} transition={{ duration: 0.25 }} className="mt-8"><div className="mb-4"><p className="text-sm font-semibold">{active}. {current.label}</p><p className="mt-1 text-sm text-stone-500">{current.hint}</p></div><UploadCard label={current.label} hint={current.hint} file={uploaded} onUpload={upload} /></motion.div></AnimatePresence><div className="mt-5 flex justify-end gap-3">{active > 1 && <Button variant="secondary" onClick={() => setActive(value => value - 1)}>Back</Button>}{active < 3 ? <Button onClick={() => setActive(value => value + 1)} disabled={!uploaded}>Continue <ArrowRight className="size-4" /></Button> : !allComplete ? <Button onClick={upload}>Confirm student answer</Button> : null}</div>{active === 3 && allComplete && <Button className="mt-6 w-full !h-14 text-base shadow-lg shadow-[#D97757]/20" onClick={() => navigate('/processing')}><FileCheck2 className="size-5" />Grade & Annotate Answer</Button>}{active === 3 && !allComplete && <p className="mt-4 text-right text-xs text-stone-400">Complete each step to unlock grading.</p>}</div> }
